### ISSUE TITLE
Getting io.grpc.StatusRuntimeException: UNKNOWN: unimplemented

### ISSUE THREAD

**Issue by Aymalla** [microsoft/durabletask-java#142] opened 2023-06-15 16:44 UTC
We're integrating with v1.1.0 for durabletask-client to support the worflow component for Dapr. We did a successful integration with most of the management Api:

- scheduleNewWorkflow
- terminateWorkflow
- getInstanceState
- waitForInstanceStart
- waitForInstanceCompletion
- raiseEvent
- purgeInstance

Except two apis returning io.grpc.StatusRuntimeException: UNKNOWN: unimplemented: 
- DurableTaskClient.queryInstances 
- DurableTaskClient.purgeInstances

Even I can see that it is supported in the [java-sdk repo](https://github.com/microsoft/durabletask-java/blob/main/client/src/main/java/com/microsoft/durabletask/DurableTaskGrpcClient.java) and [Ms doc](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=java#query-all-instances)

For queryInstances 
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.dapr.examples.DaprMainApplication.main(DaprMainApplication.java:37)
        ... 8 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: unimplemented
        ... 13 more
```
For purgeInstances:

```
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.dapr.examples.DaprMainApplication.main(DaprMainApplication.java:37)
        ... 8 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: multi-instance purge is not unimplemented
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at com.microsoft.durabletask.implementation.protobuf.TaskHubSidecarServiceGrpc$TaskHubSidecarServiceBlockingStub.purgeInstances(TaskHubSidecarServiceGrpc.java:1184)
        at com.microsoft.durabletask.DurableTaskGrpcClient.purgeInstances(DurableTaskGrpcClient.java:275)
        at io.dapr.workflows.client.DaprWorkflowClient.purgeInstances(DaprWorkflowClient.java:252)
        at io.dapr.examples.workflows.DemoWorkflowClient.main(DemoWorkflowClient.java:85)
```
Are these two APIs (queryInstances - purgeInstances) supported or not yet?
Durabletask Version: 1.1.0
Java Version: openjdk 11.0.19 
Maven Version: Apache Maven 3.8.8

**Comment by Aymalla** [comment] 2023-06-16 09:34
Thanks @cgillum !

**Comment by cgillum** [comment] 2023-06-21 00:55
I'll go ahead and close this for now since it's expected behavior.

**Closed by cgillum** 2023-06-21 00:55 UTC
