### ISSUE TITLE
scheduleNewOrchestrationInstance function doesn't throw an error if instanceId already exists

### ISSUE THREAD

**Issue by kanupriya15025** [microsoft/durabletask-java#135] opened 2023-05-15 10:37 UTC
Ideally, if there's an orchestrator function with the same instanceId already present, there should be an error thrown.

**Comment by kaibocai** [comment] 2023-05-15 15:45
Seems to be a bug, need investigation.

**Comment by kanupriya15025** [comment] 2023-05-23 15:08
@kaibocai Any updates on this?

**Comment by cgillum** [comment] 2023-06-09 23:57
I took a closer look at this with help from @kamperiadis. The problem is in the Durable extension running in the Functions host. There is a bug where code paths for out-of-proc languages are not correctly checking for existing instances. My recommendation is that we make a change [here](https://github.com/Azure/azure-functions-durable-extension/blob/292d30bf15454b36d7fa16962c36d8cb9377738e/src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs#L151-L162) to pass a list of de-dupe status values to ensure that we throw an exception for existing/running instances.

Note that this will be a breaking change that needs to be called out in the release notes.

**Comment by cgillum** [comment] 2023-06-12 18:33
I just realized that we already have a fix in PR for this issue: https://github.com/Azure/azure-functions-durable-extension/pull/2489.

**Comment by jviau** [comment] 2023-06-13 20:35
Resolved by https://github.com/Azure/azure-functions-durable-extension/pull/2489 (pending release)

**Closed by jviau** 2023-06-13 20:35 UTC
Labels: bug, need investigation

**Comment by kanupriya15025** [comment] 2023-06-28 09:58
@jviau Is this released with v1.1.1?

**Comment by kaibocai** [comment] 2023-06-28 13:21
> @jviau Is this released with v1.1.1? Because it still doesn't give me an error with same instanceId.

@kanupriya15025 , the issue is fixed in durable function extension, the repo is at https://github.com/Azure/azure-functions-durable-extension, the release that contains the fix is https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.9.6. 

In this case you need to manually update the durable function extension on your local, where you can find steps at https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-extension-upgrade#manually-upgrade-the-durable-functions-extension
